### ISSUE TITLE
wg-quick is for debian not FreeBSD

### ISSUE THREAD

**Issue by Baenwort** [glorious1/manual-connections#5]
In your readme.md you mention using this for wireguard instead of OpenVPN. 

However, in your instructions you mention wg-quick which is not a FreeBSD package but rather a Debian one. The only wireguard package for FreeBSD on FreshPorts is wireguard and wireguard-go (which if you pkg install wireguard is also installed).

I haven't tried wireguard yet but if you are using it on FreeBSD with your script what package are you using?

**Comment by CoreyVidal** [comment]
@Baenwort did you ever get an answer for this? Or get WireGuard working?

**Comment by Baenwort** [comment]
No, I haven't had time to circle back and get wireguard working. I do have this script working with openvpn currently.

**Comment by Baenwort** [comment]
@CoreyVidal I did get wireguard working. Between the changes I made in the two issue tickets and commenting out the PIA_AUTOCONNECT line and replacing it with "PIA_AUTOCONNECT=wireguard" I am currently running with wireguard and PIA.

**Comment by glorious1** [comment]
Thanks, I think I merged that, but I'm not good with github.

**Comment by Baenwort** [comment]
fix merged in
