### ISSUE TITLE
certificate error message

### ISSUE THREAD

**Issue by Baenwort** [glorious1/manual-connections#6]
So this has been working for several months now for me but it is now giving a error about the crt you include.

/manual-connections # curl -vs -u p8086016:LLZXxt6urAcHCjCfhu --cacert ca.rsa.4096.crt --connect-to ontario407::172.98.80.2: https://                                 ontario407/authv3/generateToken
* Connecting to hostname: 172.98.80.2
*   Trying 172.98.80.2:443...
* Connected to 172.98.80.2 (172.98.80.2) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: ca.rsa.4096.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0

**Comment by glorious1** [comment]
Did you ever figure this out?  I haven't had this issue, though I haven't tried curl to investigate.

**Comment by Baenwort** [comment]
No, I switched to Wireguard which fixed the problem for me.
